urlweb:           "https://AndreSeptiano.github.io/os211/"
urlgithub:        "https://github.com/AndreSeptiano/os211/"
urlghpage:        "https://AndreSeptiano.github.io/os211/"
keywords:         "jekyll, testing"
